### ISSUE TITLE
 native memmory leak still open in v1.0.11 (closed at #23)

### ISSUE THREAD

**Issue by tonggang2013** [wseemann/FFmpegMediaMetadataRetriever#117]
public static Bitmap getVideoEndThumbnail(String filePath) {
        Bitmap bitmap = null;
        FFmpegMediaMetadataRetriever retriever = new FFmpegMediaMetadataRetriever();
        try {
            retriever.setDataSource(filePath);
            FFmpegMediaMetadataRetriever.Metadata metadata = retriever.getMetadata();
            String durationStr = metadata.getString(FFmpegMediaMetadataRetriever.METADATA_KEY_DURATION);
            bitmap = retriever.getFrameAtTime(Integer.valueOf(durationStr) * 1000, FFmpegMediaMetadataRetriever.OPTION_PREVIOUS_SYNC);
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            try {
                retriever.release();
            } catch (RuntimeException e) {
                e.printStackTrace();
            }
        }
        return bitmap;
    }

heap memory not be released.   
ffmpeg sdk version: v1.0.11

**Comment by sonadora** [comment]
It took me about 2 months to solve this problem.
Unfortunately it can only be fixed by modifying the original project file.
I still cannot find a way to solve it by using the prebuilt library.

Here is my solution:
1. Clone the whole project to my computer.
2. Add the library as a module to my project (An android project,and I use Android Studio).
3. I change the ffmpeg from version 3.0.1 to version 3.1.3( the lastest version) by editing the "FFmpegMediaMetadataRetriever/gradle/fmmr-library/library/src/main/ffmpeg/build_ffmpeg.sh".
Upgrade the ffmpeg version can reduced the memory leak problem. But just delay the time that all memory was consumed.
4. This is the most important part. I modified "FFmpegMediaMetadataRetriever/gradle/fmmr-library/library/src/main/jni/metadata/ffmpeg_mediametadataretriever.c".
Add the folowing code in function "void release(State **ps) " after the line with code `if(state){ `

`if(state->video_st){`
`	if(state->video_st->codec != NULL) {`
`		avcodec_close(state->video_st->codec);`
`		// Do not free here. Crash.`
`//		av_free(state->video_st->codec)`
`	}`
`}`
`if(state->audio_st) {`
`	if(state->audio_st->codec) {`
`		avcodec_close(state->audio_st->codec);`
`		// Do not free here. Crash.`
`//		av_free(state->video_st->codec)`
`	}`
`}`

There are some other code I changed at other place in the same file. But they are not quite necessarily for fixing the issue. I attach the patch for those want to solve the problem immediately with the source code. Put the fix at "FFmpegMediaMetadataRetriever/gradle/fmmr-library/library/src/main/jni/" and patch the file.
[memory_leak_fix.txt](https://github.com/wseemann/FFmpegMediaMetadataRetriever/files/539397/memory_leak_fix.txt)

If it is hard to understand what I am saying, wait for the project manager test and accept my patch.

Please note: I test this only on my android 6.x phone with MP4 video file (codec: h.264 & aac). Not guaranteed for other environment.

**Comment by wseemann** [comment]
I merged a subset of the pull request. This should address the leak. Thank you for testing and submitting these changes.
