### ISSUE TITLE
Define a method with params (width, height)

### ISSUE THREAD

**Issue by van416** [wseemann/FFmpegMediaMetadataRetriever#21]
Thanks for The great share~
if this method follow exist：
getFrameAtTime(long time, int width, int height, int options);
it will be help for me~

**Comment by jmgirven** [comment]
If I were to perform getFrameAtTime on a very high resolution, e.g. 4k video, I would have to load in a 4k image into memory before then programatically downscaling it to the size of my ImageView as you suggest. I am not hugely familiar with the internals of this library, or probably more importantly FFmpeg, but wouldn't specifying a size to FFmpeg on image creation lead to a reducation in memory usage? Do you know the answer?

I was also reading about loading in bitmaps efficiently from this doc:

http://developer.android.com/training/displaying-bitmaps/load-bitmap.html

but to perform the method they suggest, instead of this library returning a bitmap, I would need an InputStream / file / etc. Is that an alternative?

I am asking because I am loading in a gallery of image thumbnails from a user video. After loading in the frame using getFrameAtTime, I downscale it using:

```java
    Bitmap bitmap = null;
    FFmpegMediaMetadataRetriever retriever = new FFmpegMediaMetadataRetriever();
    try {
        retriever.setDataSource(context, uri);
        bitmap = retriever.getFrameAtTime(timeUs, FFmpegMediaMetadataRetriever.OPTION_CLOSEST);
    } finally {
        retriever.release();
    }
    return ThumbnailUtils.extractThumbnail(bitmap, width, height);
```

and set it to an ImageView. This is potentially a lot of 4k bitmaps (at least temporarily) going into memory!
