### ISSUE TITLE
App is crashing while extracting frames with FFmpeg

### ISSUE THREAD

**Issue by ArtanBerisha1** [wseemann/FFmpegMediaMetadataRetriever#240]
I am using FFmpeg to extract frames from video in Android,

Gradle Dependencies:
```
    implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-core:1.0.15'
    implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-native:1.0.15'
```

```
for (index in 0 until number_of_frames_to_capture) {
      bitmap = retriever?.getFrameAtTime((index * (1000000 / frames_per_seconds)).toLong(), FFmpegMediaMetadataRetriever.OPTION_CLOSEST)
      if (bitmap != null) {
           saveImageInExternalDrive(bitmap, System.currentTimeMillis())
      }
}
retriever.release()
```

The OS is killing my app with the error: "I/Zygote: Process 9770 exited due to signal (9)" , that means there is a memory issue with my app. To extract 1 frame is taking around 1 second (and when I try to process a video with 3-6 min, it takes around 2 hours to finish the process, -> it fails as soon as it extracts around 1300 frames ) and I think this is the issue, so is this something that should happen or not ?
Also I am not getting any other error so I don't know where the problem is exactly.

**Comment by wseemann** [comment]
Without seeing exactly how you are using the library it's not possible for me to determine if the leak is in my library or your code. In the instance of @ArtanBerisha1 code, he's not calling `bitmap.recycle()` after each iteration which could result in a OOM error. More so, it's likely taking more time than expected since he's performing an additional IO operation and writing the bitmap to disk for each iteration.

@Den-Rimus given that you just reported this issue today, and clearly would like my help debugging the issue, it seems strange that you would hop over to Stackoverflow and [bash my library](https://stackoverflow.com/questions/20376321/mediametadataretriever-always-returns-null-when-trying-to-retrieve-a-frame/20384000?noredirect=1#comment134382516_20384000) on an unrelated post before giving me a chance to respond or ask for more information. This library took several years to make, it's very complex, and I wrote it all by myself. It's easy to sit behind a computer and be critical of someone else's work, but just remember, you have a job and companies like yours (ScanBot) make money off of hardworking people like myself that pour years of their free time into be something just for it to be met with constant criticism and dissatisfaction from people like yourself that contribute nothing back to the projects they use.

**Comment by ArtanBerisha1** [comment]
Hi @wseemann , 
Since this was more than 2 years ago I can't remember exactly how I solved it but one thing for sure the issue wasn't on library side, it was on my part(probably smth with bitmaps), so I am guessing we can close this issue. (Forgot to close this at the time and write the fix of my issue)
