### ISSUE TITLE
UnsatisfiedLinkError - libavutil.so

### ISSUE THREAD

**Issue by PFittech** [wseemann/FFmpegMediaMetadataRetriever#70]
I put dependencie com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.1 I then i get error:

 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dev.franek.pavol.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dev.franek.pavol.myapp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libavutil.so"

I do not know if this is bug or I do something bad .(

Galaxy S6 - Android 5.1.1. 
Stock ROM. 
compileSdkVersion 23
buildToolsVersion "23.0.1"

**Comment by wseemann** [comment]
Fixed in latest release.

**Comment by PFittech** [comment]
No problem is still there.

**Comment by gmcbay** [comment]
I had this same problem and it turned out to be due to having another JNI dependency that included arm64-v8a libraries and FfmpegMediaMetadataRetriever not having an arm64 build in the prepacked gradle version.   

arm64 phones (like the new Nexus 6 version) can fall back to 32-bit shared libs but if you have at least one arm64 shared lib it assumes all libraries will have arm64 builds and throw this linker exception if any don't.

I solved it via the steps on this blog post (not my own blog): 

https://corbt.com/posts/2015/09/18/mixing-32-and-64bit-dependencies-in-android.html
